# Generated by Django 6.0.3 on 2026-03-17 19:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('token_qr', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.disciplina')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.sala')),
            ],
        ),
    ]
