# Generated by Django 6.0.3 on 2026-04-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='peso_aula',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
