# Generated by Django 6.0.3 on 2026-04-30 20:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_rename_carga_horaria_disciplina_carga_horaria_total_and_more'),
        ('classes', '0002_aula_peso_aula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='academic.turma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
