# Generated by Django 6.0.3 on 2026-05-31 21:46

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_historicalcourse_historicaldepartment_and_more'),
        ('classes', '0003_remove_aula_disciplina_aula_turma_alter_aula_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAula',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('peso_aula', models.PositiveIntegerField(default=2)),
                ('token_qr', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('last_token_update', models.DateTimeField(blank=True, editable=False)),
                ('encerrada_manualmente', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academic.sala')),
                ('turma', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academic.turma')),
            ],
            options={
                'verbose_name': 'historical aula',
                'verbose_name_plural': 'historical aulas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
