# Generated by Django 6.0.3 on 2026-04-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='status',
            field=models.CharField(choices=[('VALIDA', 'Válida'), ('INVALIDA', 'Inválida')], default='VALIDA', max_length=20),
        ),
    ]
