# Generated by Django 6.0.3 on 2026-05-02 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_aula_disciplina_aula_turma_alter_aula_data'),
        ('presence_service', '0002_alter_presenca_status'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presenca',
            options={'verbose_name': 'Presença', 'verbose_name_plural': 'Presenças'},
        ),
        migrations.RenameField(
            model_name='presenca',
            old_name='horario_registro',
            new_name='data_registro',
        ),
        migrations.AlterUniqueTogether(
            name='presenca',
            unique_together={('aluno', 'aula')},
        ),
        migrations.AlterField(
            model_name='presenca',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='users.aluno'),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_registradas', to='classes.aula'),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='ip_registrado',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='status',
        ),
    ]
