# Generated by Django 6.0.3 on 2026-06-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historicalaluno_historicalprofessor_historicaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofessor',
            name='siape',
            field=models.CharField(blank=True, db_index=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='siape',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalaluno',
            name='matricula',
            field=models.CharField(db_index=True, max_length=11),
        ),
    ]
