# Generated by Django 6.0.3 on 2026-06-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_aluno_endereco_aluno_nome_mae_aluno_nome_pai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='language_preference',
            field=models.CharField(choices=[('pt-br', 'Português'), ('en', 'English')], default='pt-br', max_length=10),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='theme_preference',
            field=models.CharField(choices=[('default', 'Padrão (Futurista)'), ('light', 'Claro'), ('dark', 'Escuro')], default='default', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('pt-br', 'Português'), ('en', 'English')], default='pt-br', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('default', 'Padrão (Futurista)'), ('light', 'Claro'), ('dark', 'Escuro')], default='default', max_length=10),
        ),
    ]
