# Generated by Django 6.0.3 on 2026-06-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_historicaluser_language_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='language_preference',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language_preference',
        ),
    ]
