# Generated by Django 6.0.3 on 2026-06-11 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_historicaluser_language_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='theme_preference',
        ),
        migrations.RemoveField(
            model_name='user',
            name='theme_preference',
        ),
    ]
