# Generated by Django 6.0.3 on 2026-03-17 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='professor_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professor'),
        ),
    ]
