# Generated by Django 6.0.3 on 2026-04-23 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_course_department_disciplina_course_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='professor_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='users.professor'),
        ),
    ]
