# Generated by Django 6.0.3 on 2026-04-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_disciplina_professor_responsavel'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='disciplinas_matriculadas', to='users.aluno'),
        ),
    ]
