# Generated by Django 6.0.3 on 2026-04-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_disciplina_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='historicaldisciplina',
            name='carga_horaria',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
