# Generated by Django 6.0.3 on 2026-04-30 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_disciplina_carga_horaria_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='carga_horaria',
            new_name='carga_horaria_total',
        ),
        migrations.RenameField(
            model_name='historicaldisciplina',
            old_name='carga_horaria',
            new_name='carga_horaria_total',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='professor_responsavel',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='historicaldisciplina',
            name='professor_responsavel',
        ),
        migrations.RemoveField(
            model_name='historicaldisciplina',
            name='semestre',
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='academic.course'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=10)),
                ('ativa', models.BooleanField(default=True)),
                ('alunos', models.ManyToManyField(blank=True, related_name='turmas_matriculadas', to='users.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_ativas', to='academic.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_turmas', to='users.professor')),
            ],
        ),
    ]
