# Generated by Django 6.0.3 on 2026-06-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_historicalcourse_historicaldepartment_and_more'),
        ('users', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='professores_responsaveis',
            field=models.ManyToManyField(blank=True, related_name='disciplinas_sob_responsabilidade', to='users.professor'),
        ),
    ]
